import '@/app/styles/collection.css'
import '@/app/styles/collections.css'
import '@/app/styles/dashboard.css'
import '@/app/styles/figurine.css'
import '@/app/styles/navbar.css'
import '@/app/styles/index.css'

import AuthProviders from './components/AuthProviders';
import Navbar from './components/Navbar';

export const metadata = {
  title: 'Pop Masters',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <AuthProviders>
          <Navbar />
          {children}
        </AuthProviders>

      </body>
    </html>
  )
}
